### ISSUE TITLE
小米3（1920*1080） 选日期和时间数字宽度不够造成文字重叠

### ISSUE THREAD

**Issue by pangli** [saiwu-bigkoo/Android-PickerView#1]

**Comment by saiwu-bigkoo** [comment]
我这用小米3测试没发现这个问题，你可以尝试修改WheelTime里面new NumericWheelAdapter的两个数值，另外还可以修小一点textSize

**Comment by saiwu-bigkoo** [comment]
我这用小米3测试没发现这个问题，你可以尝试修改WheelTime里面new NumericWheelAdapter的两个数值，另外还可以修小一点textSize

**Comment by saiwu-bigkoo** [comment]
我这用小米3测试没发现这个问题，你可以尝试修改WheelTime里面new NumericWheelAdapter的两个数值，另外还可以修小一点textSize

**Comment by saiwu-bigkoo** [comment]
我这用小米3测试没发现这个问题，你可以尝试修改WheelTime里面new NumericWheelAdapter的两个数值，另外还可以修小一点textSize

**Comment by pangli** [comment]
我使用的是全日期，xxxx年xx月xx日xx时xx分时出现的这种问题
