### ISSUE TITLE
省市级三级联动，地址过长的地址，比如，过瘾格勒蒙自治州就会字体显示不全，

### ISSUE THREAD

**Issue by chaodongyang** [saiwu-bigkoo/Android-PickerView#100]
省市级三级联动，地址过长的地址，比如，过瘾格勒蒙自治州就会字体显示不全，

**Comment by chaodongyang** [comment]
省市级三级联动，地址过长的地址，比如，过瘾格勒蒙自治州就会字体显示不全，

**Comment by QIWANG-2015** [comment]
我想问一下，如何通过网络获取数据，并利用这个显示出来

**Comment by QIWANG-2015** [comment]
我想问的是如何根据服务器的数据动态的加载显示数据

**Comment by saiwu-bigkoo** [comment]
@QIWANG-2015 跟例子一样，加载数据完成后配置控件，把ArrayList<你的网络获取对应的JavaBean> set 进去就行了，javabean中要实现
public String getPickerViewText() {
        return 内容;
    }

**Comment by QIWANG-2015** [comment]
@saiwu-bigkoo 谢啦，我回去试试，有问题我还会回来问的 :)
