### ISSUE TITLE
在使用省市区时，如何通过网络获取数据

### ISSUE THREAD

**Issue by QIWANG-2015** [saiwu-bigkoo/Android-PickerView#102]

**Comment by QIWANG-2015** [comment]
在使用省市区时，如何通过网络获取数据，并且通过这个显示出来

**Comment by saiwu-bigkoo** [comment]
获取数据，你的javabean写getPickerViewText 函数，就是展示出来的文字数据了。然后直接set这个javabean对应的list进去
