### ISSUE TITLE
如何设置OptionsPickerView字体大小

### ISSUE THREAD

**Issue by BruceeWang** [saiwu-bigkoo/Android-PickerView#105]
我尝试通过OptionsPickerView.findviewById去找到控件，然后settextsize，但是不知道这样找到了，如何关联到OptionsPickerView上去。

**Comment by saiwu-bigkoo** [comment]
重写 pickerview_customTextSize 和 pickerview_textsize 到 xml 中 来控制自定义文字大小

**Comment by BruceeWang** [comment]
谢谢你的回答，我通过studio gradle compile导入代码包。貌似不可以修改那些代码

**Comment by LomoLin** [comment]
在bools.xml文件中覆写pickerview_customTextSize ，设置为true;
在dimens.xml文件中覆写pickerview_textsize 为你想要设置的值。
@BruceeWang

**Comment by BruceeWang** [comment]
谢谢了 我试试
@LomoLin

**Comment by BruceeWang** [comment]
同样也谢谢你的回答
@saiwu-bigkoo
