### ISSUE TITLE
太感谢了，很好用的控件。不过希望能给出一些自定义的功能。

### ISSUE THREAD

**Issue by zhpanvip** [saiwu-bigkoo/Android-PickerView#107]
最近再做一个省市区的三级联动，很幸运发现了您写的这个控件，用起来很方便，效果也相当好。不过感觉还是有点不足的是貌似不能自定义三级联动的界面。不知道是不是我没找到如何修改的？比如可以自定义“取消”和”确定“文字大小，颜色。自定义滚轮中内容的字体大小和颜色和文字过长时使用省略号。总之还是要感谢的。希望这个空间也会优化的越来越好！

**Comment by saiwu-bigkoo** [comment]
文字过长使用省略号可以通过 在javabean里面 写 getPickerViewText 函数自己进行截取
