### ISSUE TITLE
日期选择能否增加 年月 两个值的选择

### ISSUE THREAD

**Issue by xuhuan** [saiwu-bigkoo/Android-PickerView#12]
如题，就是只出现 年月 两个选项，如：
```
2015-10
```
还有能否增加 至今 选项。

**Comment by saiwu-bigkoo** [comment]
你好，应你要求增加了年月的格式，请看1.0.2版本

**Comment by xuhuan** [comment]
谢谢，年月试过了可用。
能否在确定按钮旁边增加
```
至今
```
按钮,或者设计成可自定义增加按钮的方式，用于扩展功能。

**Comment by saiwu-bigkoo** [comment]
你可以用源码方式自己拓展一下这个按钮，因为我觉得时间具体选择和至今的概念不同的，强加上体验不好，并不适用众多需求。

**Comment by xuhuan** [comment]
概念不同所以在考虑是否做成可扩展的按钮，按钮里具体的逻辑可以根据业务进行自定义。
那我fork一份出来修改下看看。jcenter是不是不允许同名包存在的？不能的话需要修改包名发布。
这个项目是什么协议的，MIT or 其他？

**Comment by saiwu-bigkoo** [comment]
MIT

**Comment by xuhuan** [comment]
OK.

ps:顺带问下 Android-SVProgressHUD 这个最低能支持9+不，目前是14+的。

**Comment by saiwu-bigkoo** [comment]
这个我还没有时间修改，该项目存在内存泄漏问题，我晚点修复的时候降版本吧

**Comment by xuhuan** [comment]
嗯，期待ing...
