### ISSUE TITLE
控件不带动态更新

### ISSUE THREAD

**Issue by xiedong** [saiwu-bigkoo/Android-PickerView#125]
大神，我写着写着发现，您写的这个控件不带动态更新，有一种情况好像处理不了，控件只能在onCreat();里初始化才能用，比如我有一种情况，进入一个界面，加载界面完毕后，点击一个按钮请求城市数据，再

pvOptionsBranchBank.setPicker(branchBankListData);，数据显示不出来，这是这个控件的缺陷吧。

**Comment by saiwu-bigkoo** [comment]
嗯，只能请求回来数据再new 这个控件了
