### ISSUE TITLE
时间初始化无效

### ISSUE THREAD

**Issue by xuhuan** [saiwu-bigkoo/Android-PickerView#13]
```
pwTime.showAtLocation(tvTime, Gravity.BOTTOM, 0, 0,new Date());
```
上面这句的new Date() 替换成其他时间，弹出的时候的初始化依旧是当前时间。
用 setTime 也无效。每次显示都依旧是当前最新时间。

```
pwTime = new TimePopupWindow(this, Type.YEAR_MONTH_DAY);
```
时间类型选的是年月日。

还有时间类型的按钮上方少一条灰色的线，掌上生活界面是看到有的。
![image](https://cloud.githubusercontent.com/assets/1960194/10365233/6bbce3aa-6df4-11e5-83d1-b4d98dd906d2.png)

![image](https://cloud.githubusercontent.com/assets/1960194/10365344/4ec62c88-6df5-11e5-8269-d3ba735244db.png)

**Comment by saiwu-bigkoo** [comment]
hello，我刚刚测试过，设置时间是可以的，请看demo的例子：
//弹出时间选择器
        tvTime.setOnClickListener(new OnClickListener() {

            @Override
            public void onClick(View v) {
                pwTime.showAtLocation(tvTime, Gravity.BOTTOM, 0, 0,new Date());
            }
        });
关键一句  pwTime.showAtLocation(tvTime, Gravity.BOTTOM, 0, 0,new Date());   这里点击时间弹出设置了new Date()当前时间，替换成其他时间是可以设置的哦～

**Comment by xuhuan** [comment]
看后我重新调试了一下，发现是我传入的时间有问题，功能是正常的。
不过新版本最上面的横线依旧没有，这个是要自己定义的嘛？

**Comment by saiwu-bigkoo** [comment]
线的问题，我不加上是因为我最初的想法是，整个屏幕背景变半透明，这样就不加顶部线也能区分弹出控件的边界。

**Comment by xuhuan** [comment]
目前遮罩有了没的？有遮罩的话也可以。
