### ISSUE TITLE
滑动到底部有卡顿的感觉,求大神解决

### ISSUE THREAD

**Issue by yyzl0418** [saiwu-bigkoo/Android-PickerView#138]

**Comment by pihat** [comment]
可以看看WheelView这个类，在onTouchEvent里的MOVE事件修改一下
`  if (totalScrollY - itemHeight * 0.3 < top) {
                        top = totalScrollY - dy;
                    } else if (totalScrollY + itemHeight * 0.3 > bottom) {
                        bottom = totalScrollY - dy;
                    }`
我把这段代码注释掉了

**Comment by yyzl0418** [comment]
感谢
