### ISSUE TITLE
分钟自定义间隔

### ISSUE THREAD

**Issue by hwtl** [saiwu-bigkoo/Android-PickerView#14]
您好这款组件是否可以提供一个自定义分钟的滑动间隔数，比如说起点是00 05 10 xx 55
这种分钟每格为5分钟的滚轮

**Comment by saiwu-bigkoo** [comment]
hey，是可以的，你可以使用条件选择器来伪装成 时间选择器，你可以参考《影约》这款软件的发布约会时候时间选择间隔，这也是用这个控件的。发挥你的想象力～
