### ISSUE TITLE
这个popwindow弹出的时候都会在最底层，被其他的popwindow覆盖了，然后点不到了。

### ISSUE THREAD

**Issue by xiaolongonly** [saiwu-bigkoo/Android-PickerView#151]
大写的尴尬。。。。

**Comment by xiaolongonly** [comment]
我在想能不能自定义布局
![image](https://cloud.githubusercontent.com/assets/12853050/19383364/81585cfa-9236-11e6-8e31-7d56636d6035.png)看了一下是因为这个的问题。。。

**Comment by yumi0629** [comment]
@xiaolongonly 这个控件根本就不是 一个popupWindow

**Comment by xiaolongonly** [comment]
@yumi0629 ~嗯嗯~ 我想问有没有办法解决覆盖问题= =~

**Comment by pihat** [comment]
@xiaolongonly 继承BasePickerView类然后修改为PopupWindow就可以了，感觉BasePickerView写得不大好拓展，我也改动了点BasePickerView。按理来说用BottomSheet也可以实现，没试过。

**Comment by xiaolongonly** [comment]
@pihat 好的，谢谢啦~~

**Comment by Danniel-yan** [comment]
> BasePickerView

您好 遇到了同样的问题 BasePickerView具体怎么修改呢 非常感谢
