### ISSUE TITLE
通过代码重新设置 wheelview 字体大小导致变形

### ISSUE THREAD

**Issue by liuzheng9110** [saiwu-bigkoo/Android-PickerView#152]
通过 findViewById 获取 WheelView，再设置 textsize 导致会导致滚轮变形，跟了源码发现是 WheelOptions line 80 设置 wv 字体大小有关系，注释就没好了，求解？ @saiwu-bigkoo

**Comment by saiwu-bigkoo** [comment]
在bools.xml文件中覆写pickerview_customTextSize ，设置为true;
在dimens.xml文件中覆写pickerview_textsize 为你想要设置的值。
