### ISSUE TITLE
修改3D效果的问题

### ISSUE THREAD

**Issue by sweet2o09** [saiwu-bigkoo/Android-PickerView#157]
你好,我在使用你的控件的时候遇到几个问题
1.控件默认显示的时间太多了,我看了下,修改WheelView下的itemsVisible参数可以办到,不过不能设置成偶数
2.未选中的文字感觉太倾斜了,不知道要修改哪个参数才能让它显示得"直立"一些

**Comment by saiwu-bigkoo** [comment]
1.没明白2.你的意思是这个3D太曲了吧？你可以尝试调整一下源码WheelView中显示的条目。

**Comment by sweet2o09** [comment]
是的太曲了,我已经修改了itemsVisible这个参数,但是没有效果,

**Comment by sweet2o09** [comment]
itemsVisible默认是11,我修改成5,但是未选中的文字依然感觉太曲,itemsVisible只是修改了现实的条数,好像不会对曲度产生影响

**Comment by Smartlll** [comment]
这个3D效果是否可以取消掉啊

**Comment by largeCabbage** [comment]
怎樣取消3D效果

**Comment by saiwu-bigkoo** [comment]
你用1.x版本就可以了
