### ISSUE TITLE
滑动的幅度太大问题

### ISSUE THREAD

**Issue by nashxk** [saiwu-bigkoo/Android-PickerView#17]
当选项只有几个的时候，迅速上滑下滑所有选项会消失，然后过1秒左右才回来，请问有解决方法么？ios原生的没有这个问题。掌上生活也没有这个问题。。

或者说怎么控制WheelView的滑动幅度？

**Comment by saiwu-bigkoo** [comment]
WheelView.class 里面可以调节下
        /** Scrolling duration */
	private static final int SCROLLING_DURATION = 400;

	/** Minimum delta for scrolling */
	private static final int MIN_DELTA_FOR_SCROLLING = 1;

**Comment by liuxuesong001** [comment]
不倒入包，请问怎么修改？
