### ISSUE TITLE
建议大家不要使用这个，样式写死直接加到decorView，内存泄露，逻辑混乱……

### ISSUE THREAD

**Issue by justforsoy** [saiwu-bigkoo/Android-PickerView#174]
本来想省事用一下，然后改造加改bug的时间……不如自己重写了

**Comment by stormlei** [comment]
@justforsoy 你有更好的选择？你用的哪个

**Comment by yhaos** [comment]
@justforsoy  请问：您有更好的选择？您现在在用的哪个？

**Comment by xiongwenzhi** [comment]
同问，有那个更好的开源的吗

**Comment by justforsoy** [comment]
现在想一下，如果重新开发的话，我会说服我们的设计，时间选择使用android 风格的TimePicker。
位置选择如果可以跳界面，使用列表（google的app、微信、美团什么的都这样），如果一定要弹框，其实可以用自己写或者用NumberPicker（它不止可以显示数字的）来实现。

**Comment by xiongwenzhi** [comment]
那要是4.4的时间选择，那好难看啊，5.0以后倒还行，但是不好用啊
