### ISSUE TITLE
为什么在 直接使用gradle 依赖:     compile 'com.bigkoo:pickerview:2.0.3' 引用报错

### ISSUE THREAD

**Issue by wei6718189** [saiwu-bigkoo/Android-PickerView#28]
报了一个fail to resolve: compile 'com.bigkoo:pickerview:2.0.3 
error(30,13) show in File
                    show in project structure dialog

**Comment by saiwu-bigkoo** [comment]
额，重新试试

**Comment by saiwu-bigkoo** [comment]
会不会少了最后一个‘引号’？

**Comment by wei6718189** [comment]
我直接拷贝过去的 您那边没有问题吗 ？

**Comment by saiwu-bigkoo** [comment]
没问题哦，我看你打出的错误，fail to resolve: compile 'com.bigkoo:pickerview:2.0.3    你是不是拷贝漏了最后一个 引号，完整的是   compile 'com.bigkoo:pickerview:2.0.3'
