### ISSUE TITLE
WheelOptions当滚轮字数超过两个时，会出现文字重叠，但滑动后恢复

### ISSUE THREAD

**Issue by chenshixin** [saiwu-bigkoo/Android-PickerView#3]
滚动前
![2015-06-11 3 06 24](https://cloud.githubusercontent.com/assets/8465355/8101610/7691fe84-104b-11e5-96c1-a06591b57b93.png)

滚动后
![2015-06-11 3 07 50](https://cloud.githubusercontent.com/assets/8465355/8101639/b541a47c-104b-11e5-9b70-d7eecfd428b2.png)

**Comment by chenshixin** [comment]
修改ArrayWheelAdapter的DEFAULT_LENGTH即可

**Comment by xiaozhi003** [comment]
Thanks
