### ISSUE TITLE
时间控件如何加入上下限啊？？？

### ISSUE THREAD

**Issue by loquaciouser** [saiwu-bigkoo/Android-PickerView#30]
指定时间控件在指定范围内滚动，比如：2015-05-06 19:00 ~ 2915-12-10 17:30

**Comment by saiwu-bigkoo** [comment]
Time那个View 有两个函数你找下
       public static void setSTART_YEAR(int sTART_YEAR) {
		START_YEAR = sTART_YEAR;
	}

	public static void setEND_YEAR(int eND_YEAR) {
		END_YEAR = eND_YEAR;
	}

**Comment by loquaciouser** [comment]
你那只能控制 年限。我要求具体的 时间戳2015-05-06 19:00 ~ 2017-12-10 17:30。。。要控制 月份、天、时、分的范围

**Comment by saiwu-bigkoo** [comment]
那目前还不支持呢，你可以下载源码再拓展一下这个功能
