### ISSUE TITLE
2.0不支持自定义选项字体颜色?

### ISSUE THREAD

**Issue by bf3400** [saiwu-bigkoo/Android-PickerView#32]
我通过xml方式可以覆盖布局,实现自定义背景及标题栏背景,但是选项文字颜色无法自定义, 只能修改源码?
com.bigkoo.pickerview.lib.WheelView: line(129):
        colorGray = 0xffafafaf;
        colorBlack = 0xff313131;
        colorLightGray = 0xffc5c5c5;
![image](https://cloud.githubusercontent.com/assets/5080247/11770140/901b2924-a232-11e5-9a8b-67657c19669c.png)
![image](https://cloud.githubusercontent.com/assets/5080247/11770160/ae8d0a6c-a232-11e5-99a1-246228bc0d99.png)

**Comment by bf3400** [comment]
![image](https://cloud.githubusercontent.com/assets/5080247/11770466/b1a365a0-a239-11e5-9532-b4ec492e05d6.png)
只能修改源码了

**Comment by saiwu-bigkoo** [comment]
选项文字是我疏忽了，没写在xml，下版本我再添加进去，谢谢提醒。

**Comment by saiwu-bigkoo** [comment]
新版本颜色加入了xml，你可以升级了
