### ISSUE TITLE
性能与1.x相比 有很大问题

### ISSUE THREAD

**Issue by hackill** [saiwu-bigkoo/Android-PickerView#33]
pick range  100-1000 
101 102.。。。。1000
两个问题。
1。弹框出来的太慢 ，卡ui
2。滑动选择太慢，比如从500 要选择100，简直要滑到死

1.x 不会有这样的问题

**Comment by hackill** [comment]
range 较大的时候，比较卡ui ，demo没问题。

**Comment by saiwu-bigkoo** [comment]
1.弹框这个动画时间跟之前是一样的，没有改动过。如果是滑动卡我倒理解，因为比1.x界面绘制复杂了。
2.如果慢的话，你可以自己修改下WheelView里面VELOCITYFLING的值。

**Comment by hackill** [comment]
感谢你的回复。
应该不是弹窗的动画时间问题。range小的时候弹出和滑动很流畅。 range大的时候，应该是创建view的过程消耗时间过久。滑动不卡，只是很慢一次只能滑动几个item，就算item非常长也是如此。
大神，可以试一下选择 1-1000中任意一个数。 
我现在改回了1.x，急着用，有时间再去探讨2.x的奥秘
