### ISSUE TITLE
OptionsPickerView,当optionItems的长度为6(其他长度不会出现这样的问题)的时候,可以滑到第7个条目上去，

### ISSUE THREAD

**Issue by lnj721** [saiwu-bigkoo/Android-PickerView#34]
roomPickView = new OptionsPickerView(ActivitySelectSeat.this);
   roomPickView.setPicker(strRoomList);
   roomPickView.setTitle("选择台号");
   roomPickView.setCyclic(false);
   roomPickView.setSelectOptions(0);
OptionsPickerView是这样初始化的

**Comment by saiwu-bigkoo** [comment]
2.0.4已修复超出范围问题，请升级

**Comment by saiwu-bigkoo** [comment]
2.0.5才对
