### ISSUE TITLE
Dialog样式的Activity中使用问题

### ISSUE THREAD

**Issue by Saxxhw** [saiwu-bigkoo/Android-PickerView#35]
您好，按照您目前的这种对话框实现方式，在Dialog样式的Activity中展示有问题，可以测试一下，日期选择对话框实在dialog样式activity的底部弹出的，而不是在屏幕底部弹出。
建议最好还是用dialog去实现弹窗

**Comment by saiwu-bigkoo** [comment]
Dialog样式的Activity 原本就是已经是弹窗了，在弹窗中再加上 另外一个全屏弹窗原本就是用户体验极差的，所以主版本不考虑改为dialog来支持这种方式，你可以修改源码进行支持。
