### ISSUE TITLE
选择最后或者第一个的时候滚轮会一直抖动(2.0.6)

### ISSUE THREAD

**Issue by NaughtBoy** [saiwu-bigkoo/Android-PickerView#37]
*在选择最后一个Item的时候，滚轮一直抖动。这个不管是demo还是我自己自定义的都会这样。
*然后另外一个问题，我自己根据时间选择器改造的一个demo，当月份只有3个item的时候，第一个会选不到，然后会一直抖动，选不到的我现在不知道是我的代码问题还是库的问题。

*原谅渣渣的我直接用百度网盘分享录屏给你：{http://pan.baidu.com/s/1qWRbGLm}

**Comment by NaughtBoy** [comment]
我又试了一下，把demo里面的时、分分别改成2个和3个，也会出问题

**Comment by NaughtBoy** [comment]
那个第一个不能选中的问题我解决了，是我代码的问题。设置setCurrentItem()的时候大于当前的条目数量，导致onTouch事件的move动作用initPosition计算bottom得到一个负数。在条目那里加上判断就OK了。

**Comment by NaughtBoy** [comment]
另一个问题：为什么在WheelTime里面添加年、月的监听里面，每一次切换adapter都要重新new 一遍？复用不会更好吗？

**Comment by saiwu-bigkoo** [comment]
我也是醉了，我测试了下，没有抖动问题，我也是设了，2个3个的，之前倒是有，但是我解决了，最新版按理说不会出现这个问题。能否提供你抖动代码给我测试下？

**Comment by NaughtBoy** [comment]
不好意思，这几天有些忙，暂时没办法把代码抽出来给你。
另外的，发现了一个问题。在你的 WheelView.setCurrentItem（）方法里面是不是　一句        this.selectedItem=currentItem;

**Comment by saiwu-bigkoo** [comment]
WheelView.setCurrentItem（）方法里面   不是直接this.selectedItem=currentItem;　的。滚动结束后才是selectedItem == currentItem的。

**Comment by NaughtBoy** [comment]
但是，如果我是代码里面主动调用setCurrentItem（）呢？在getTime的时候没有效果

**Comment by saiwu-bigkoo** [comment]
time的话是 setTime
