### ISSUE TITLE
通过代码隐藏有bug

### ISSUE THREAD

**Issue by eurekao** [saiwu-bigkoo/Android-PickerView#38]
<pre>
 @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if(pvSex.isShowing()||pvTime.isShowing()){
                pvSex.dismiss();
                return true;
            }
            else if(pvTime.isShowing()){
                pvTime.dismiss();
                return true;
            }
        }
        return super.onKeyDown(keyCode, event);
    }
</pre>
多点击几次后，怎么样也隐藏不了

**Comment by eurekao** [comment]
<pre>
@Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (keyCode == KeyEvent.KEYCODE_BACK) {
            if (pvSex.isShowing() || pvTime.isShowing()) {
                return true;
            }
        }
        return super.onKeyDown(keyCode, event);
    }
</pre>
只能这样临时解决

**Comment by saiwu-bigkoo** [comment]
if(pvSex.isShowing()||pvTime.isShowing())  你这判断错了吧，走不到else if(pvTime.isShowing()){ 当然隐藏不了呀

**Comment by eurekao** [comment]
打错了，是
<pre>
if(pvSex.isShowing()){
                pvSex.dismiss();
                return true;
            }
            else if(pvTime.isShowing()){
                pvTime.dismiss();
                return true;
            }
</pre>

**Comment by z416916003** [comment]
我跟你一样，发现这个问题，亲测 返回键事件处理中调用dismiss无法隐藏控件，
