### ISSUE TITLE
为什么选择12:00的时候返回的是00:00：00

### ISSUE THREAD

**Issue by guoyoujin** [saiwu-bigkoo/Android-PickerView#4]
当我选择中午12点的时候，返回的是凌晨00:00:00，请问怎么解决啊

**Comment by guoyoujin** [comment]
我已经找到了错误的地方，
public class WheelTime {
	public static DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
	public static DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm");
}
在上面时间格式化这个地方，不能是小写的hh，这样就会出现我说的那个问题，只需把他改成大写的HH即可，请采纳

**Comment by saiwu-bigkoo** [comment]
Thanks
