### ISSUE TITLE
getCurrentItem获取不到混动后的位置，一直是0

### ISSUE THREAD

**Issue by onecoders** [saiwu-bigkoo/Android-PickerView#40]

**Comment by saiwu-bigkoo** [comment]
滚动后停止了就会getCurrentItem 生效的，而且监听setOnoptionsSelectListener 就可以监听到改变的item。没停止不生效。

**Comment by onecoders** [comment]
![image](https://cloud.githubusercontent.com/assets/3477738/12034655/21eef91e-ae6f-11e5-9699-b3ce7a7afeb2.png)
对于以后开发人员遇到这样的问题，我想说，如果是自定义的WheelAdapter的，需要在自己的MODEL中添加getPickerViewText()方法，不然，滑动的的时候，currentItem一直是0，查看源码才知道是用了反射的原理，建议：在WheelAdapter<T>接口定义中，增加getItemText()方法，用来显示item 的text

**Comment by onecoders** [comment]
![image](https://cloud.githubusercontent.com/assets/3477738/12034714/dfe7b046-ae6f-11e5-8a39-b4353d0e884e.png)
用来显示的文字是通过反射来的，自定义的adapter中可以getItem只是返回一个Object

**Comment by saiwu-bigkoo** [comment]
这个是可选的，你的model有这个函数则反射使用这个函数，没有的话用object的String

**Comment by maoruibin** [comment]
同意 @onecoders 的做法！

        在WheelAdapter接口定义中，增加getItemText()方法，用来显示item 的text
