### ISSUE TITLE
Hello，您好，我发现2个地方有点问题

### ISSUE THREAD

**Issue by 377376701** [saiwu-bigkoo/Android-PickerView#41]
1.选择城市上面的城市名会是一样的名字，但是选择的时候会不一样
2.点击返回键的时候可以考虑不直接销毁Acitivity，可以给个设置参数，点击返回的时候是否finish掉当前Activity

谢谢！

**Comment by saiwu-bigkoo** [comment]
1.是不是你的数据源设置错误了，demo里面也没有你说的问题吧。
2.返回键你自己拦截，然后判断是否弹出了选择窗口，如果是你隐藏窗口不finish即可。

**Comment by 377376701** [comment]
![image](https://cloud.githubusercontent.com/assets/7800300/12259267/67a4bed6-b94f-11e5-8845-b1f1bccaae0c.png)
![image](https://cloud.githubusercontent.com/assets/7800300/12259298/a0840ed2-b94f-11e5-834e-2d762750335b.png)

**Comment by 377376701** [comment]
您可以试试滑动的时候

**Comment by saiwu-bigkoo** [comment]
理解了～谢谢反馈

**Comment by saiwu-bigkoo** [comment]
2.0.8已修复1的问题

**Comment by 377376701** [comment]
好的👌🏻！
