### ISSUE TITLE
能否增加一个字体大小设置

### ISSUE THREAD

**Issue by tanranran** [saiwu-bigkoo/Android-PickerView#42]
我试过在WheelView里面更改setTextSize(16F);  无效

**Comment by saiwu-bigkoo** [comment]
2.0.8加入了自定义文字大小效果，pickerview_customTextSize 为 true ，pickerview_textsize 为自定义文字大小。不能直接setTextSize，因为这个函数不会重新刷新界面。

**Comment by NicodeLee** [comment]
如果是时间选择，那只能修改代码的xml文件吗。不能在代码设置大小？

**Comment by saiwu-bigkoo** [comment]
是要修改xml，你只要在你主项目中的xml文件里加入 pickerview_customTextSize设为true，pickerview_textsize 设为文字大小，现在代码里面设置不了，因为代码里面设置了按每个组的宽度占的比例来改变大小了，即使调用WheelView里面的setTextSize也是会被等分计算这个逻辑覆盖，我现在加入了pickerview_customTextSize 这个来控制是不是按等分计算。

**Comment by beibeijerry** [comment]
pickerview_customTextSize 这个具体怎么用

**Comment by saiwu-bigkoo** [comment]
@beibeijerry 在你xml里面写入这个属性设置为true
