### ISSUE TITLE
反复点击滚轴crash

### ISSUE THREAD

**Issue by huazhiyuan2008** [saiwu-bigkoo/Android-PickerView#43]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
01-14 10:01:25.105 17155-17155/? E/AndroidRuntime:     at com.bigkoo.pickerview.adapter.NumericWheelAdapter.indexOf(NumericWheelAdapter.java:52)
01-14 10:01:25.105 17155-17155/? E/AndroidRuntime:     at com.bigkoo.pickerview.lib.WheelView.onDraw(WheelView.java:413)

**Comment by saiwu-bigkoo** [comment]
请问你的版本是？

**Comment by huazhiyuan2008** [comment]
compile 'com.bigkoo:pickerview:2.0.5'

**Comment by huazhiyuan2008** [comment]
![image](https://cloud.githubusercontent.com/assets/2877748/12344382/6982fa72-bb77-11e5-9cc9-028407d8ed08.png) 点击红框部分必现

**Comment by huazhiyuan2008** [comment]
暂时的解决方案：NumericWheelAdapter
	@Override
	public int indexOf(Object o){
        if (!(o instanceof Integer)) {
            LogUtils.e(o + "");
            return mPreValue;
        }
        mPreValue = (int) o;
		return (int)o - minValue;
	}

**Comment by saiwu-bigkoo** [comment]
更到最新版2.0.8即可
