### ISSUE TITLE
用DialogFragment里的按钮show的话会出现OptionsPickerView在dialog下面，OptionsPickerView无法使用

### ISSUE THREAD

**Issue by syc434432458** [saiwu-bigkoo/Android-PickerView#47]
![device-2016-01-27-132432](https://cloud.githubusercontent.com/assets/7437081/12604748/63fabc44-c4f9-11e5-93ee-5e26f470892b.png)

**Comment by saiwu-bigkoo** [comment]
这个dialog你用activity的dialog模式就可以出现了

**Comment by kainjinez** [comment]
I'm getting trouble with this. How to fix it saiwu?

**Comment by xiaosong520** [comment]
@kainjinez  please set  Activity Theme with dialog mode

**Comment by kainjinez** [comment]
@xiaosong520 thanks for fast replying. Can you guide more clearly? Set Theme for my dialog or Picker theme?

**Comment by xiaosong520** [comment]
@kainjinez <activity
            android:name="Activity"
            android:theme="@android:style/Theme.Dialog" >
        </activity>

**Comment by xiaosong520** [comment]
@kainjinez  android:theme="@android:style/Theme.Dialog"

**Comment by kainjinez** [comment]
@xiaosong520 you mean i have to change my first dialog to become an activity then set its theme similar dialog? I think this this not a good solution.

**Comment by xiaosong520** [comment]
@kainjinez 
No, you just need set current  Activity like this 
<activity
            android:name="Activity"
            android:theme="@android:style/Theme.Dialog" >

**Comment by xiaosong520** [comment]
@kainjinez <activity
            android:name=" Activity "
            Android:theme="@android:style/Theme.Dialog" >

**Comment by kainjinez** [comment]
`Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`
I got this while i am trying to set Theme.Dialog to my currentActivity which calls the first dialog.

**Comment by xiaosong520** [comment]
@kainjinez   android:theme="@style/AlertDialog.AppCompat"

**Comment by xiaosong520** [comment]
@kainjinez  Change to AppCompat style may be useful

**Comment by kainjinez** [comment]
@xiaosong520 same error like above, sir.

**Comment by xiaosong520** [comment]
@kainjinez What I thought was wrong，you need change first dialog to become an activity and then set its theme similar dialog, for now only  through this way to solve the problem

**Comment by Fomovet** [comment]
遇到同样的问题，更改主题样式也没有效果应该如何解决呢？

**Comment by Fomovet** [comment]
发现可以这么干先调用mDialog.hide();隐藏掉Dialog，然后再显示show()时间选择器，这样时间选择器就显示在最上面了，onTimeSelect(Date date, View v)回调的时候再mDialog.show();

**Comment by LukeMi** [comment]
when i use -->mTimePickerView.show() in DialogFragment, it showed under the DialogFragment, it can not refresh the dialogment's UI , so pity

**Comment by LukeMi** [comment]
Activity -------!CallBack!------DialogFragment------!TimePickerView.OnTimeSelectListene! -----mTimePickerView.show()--- someone can solve it or recomand some better wheel ?
