### ISSUE TITLE
Error:(2, 0) Cause: org/gradle/api/publication/maven/internal/DefaultMavenFactory 

### ISSUE THREAD

**Issue by tianshaokai** [saiwu-bigkoo/Android-PickerView#48]
下载了你的整个类库代码导入studio 报这个问题

**Comment by saiwu-bigkoo** [comment]
gradle版本不同的问题吧

**Comment by tianshaokai** [comment]
我注释了点gradle 配置文件可以了，我昨天想做一个dialog， 需要加入类似pickview的功能，就用了你的部分代码，希望你的pickview 可以已dialog 的形式可以使用哈哈，我就不用自己造了
