### ISSUE TITLE
选择城市的时候，如果两级联动，第2级中文字符超过3个会有问题

### ISSUE THREAD

**Issue by yanlusu** [saiwu-bigkoo/Android-PickerView#5]
第二个选项列只能显示两个中文字符，超过两个的其他字符被折行到下面了，导致界面混乱。

**Comment by chenzhenlindx** [comment]
我也遇到这个问题，当省市区过长时，第一次加载时会换行，求解

**Comment by chenzhenlindx** [comment]
你好，昨天遇到的问题我已解决。
将include_optionspicker.xml文件中的layout_width由wrap_content改成fill_parent就可以了。修改后可以影响WheelView类的onMeasure方法对宽度和高度的计算。

**Comment by yanlusu** [comment]
设置成match_parent解决了问题。
