### ISSUE TITLE
省市区的数据准备太麻烦了.

### ISSUE THREAD

**Issue by JamesLebron** [saiwu-bigkoo/Android-PickerView#52]
大神你好.看了DEMO ,觉得省市区的数据准备实在是太麻烦了.请问能给出简便的解决方案么?

**Comment by saiwu-bigkoo** [comment]
你的bean里面如果有getPickerViewText 函数则会反射使用此函数作为 文字，就不用将拿到的bean转换成String，更好的方案就没有了
