### ISSUE TITLE
在有些省市区是没有二级三级的情况下，就会有WheelOptions bug

### ISSUE THREAD

**Issue by LearKoo** [saiwu-bigkoo/Android-PickerView#53]
有一级的情况，二级三级效果应该存在，数据为空
有一级二级的情况，三级效果存在，数据为空

**Comment by ysmintor** [comment]
确实，这种效果没有处理，就也是找到对应的没有数据应该判断一下！关键是数据结构可能处理得不是很好！

**Comment by zhupengxiang** [comment]
加入空什么意思 我现在也是二三级没有数据问题

**Comment by xiaosong520** [comment]
@zhupengxiang 添加一个空字符串到List里面。

**Comment by zhupengxiang** [comment]
我现在要实现的是异步获取数据  这样貌似不行 你添加完wheelview不会显示么
