### ISSUE TITLE
控件貌似在Fragment中返回view不会自动关闭？

### ISSUE THREAD

**Issue by jeasoncar** [saiwu-bigkoo/Android-PickerView#59]
控件貌似在Fragment中返回view不会自动关闭？控件是依赖于Activity的，返回键直接是返回Activity，而不是关闭view？建议修复一下？

**Comment by saiwu-bigkoo** [comment]
你可以监听Activity的返回键来关闭。原本就是这样设计的。

**Comment by jeasoncar** [comment]
Activity的返回键来关闭是可以，但是如果fragment的层级比较多的（例如一个Activity里有四五个fragment，有一个或者多个用到时间滚轮，城市滚轮的话），控制这些滚轮的关闭就显得复杂了？

**Comment by rgdzh1** [comment]
4.1.9版本中,可以使用isDialog(true)来设置PickerView为一个Dialog, 然后修改BasePickerView.createDialog()方法中设置Dialog相对于窗口的位置, 这样Dialog效果和View的效果就是一样的了, 并且Dialog还能响应返回按钮事件, 不管该Dialog是在第几层Fragment里show出来的.
