### ISSUE TITLE
TimePickerView的一个小问题

### ISSUE THREAD

**Issue by yinge** [saiwu-bigkoo/Android-PickerView#63]
在WheelTime类中作者把DEFULT_START_YEAR和DEFULT_END_YEAR设成了final ，导致TimePickerView的setRange方法不生效，希望改一下

**Comment by saiwu-bigkoo** [comment]
DEFULT_START_YEAR 是final 没错的，不需要改。setRange 要在 setPicker 方法之前才有效果哦。
