### ISSUE TITLE
省市区三级联动显示有问题

### ISSUE THREAD

**Issue by damon-zhu** [saiwu-bigkoo/Android-PickerView#7]
如果省市区中的地名较长，例如新疆的博尔塔拉蒙古自治州，整个文字排版上就容易有问题

**Comment by saiwu-bigkoo** [comment]
建议不要搞太长的字段，或者你可以试试改小textSize把文字调小

**Comment by damon-zhu** [comment]
但是省市区这个必然要这么长啊，改小了很难看清，一些长的还是显示效果还是不好。。。。。。朱维君 ｜ Damon.zhu手机：13862097554邮箱：513809030@qq.com                             原始邮件                             发件人: sai<notifications@github.com>收件人: saiwu-bigkoo/Android-PickerView<Android-PickerView@noreply.github.com>抄送: damon-zhu<513809030@qq.com>发送时间: 2015年8月4日(周二) 16:03主题: Re: [Android-PickerView] 省市区三级联动显示有问题 (#7)建议不要搞太长的字段，或者你可以试试改小textSize把文字调小

**Comment by xiaozhi003** [comment]
能不能默认显示3到4个字符，太长的可以自动滚动显示。这样也不会有换行了，不知道作者能不能增加这样的功能，或者我们自己修改源码了：)

**Comment by guoxj** [comment]
也碰到这个问题了。有改好的么？

**Comment by guoxj** [comment]
分享下：
1.ArrayWheelAdapter.java里面有个ArrayWheelAdapter.DEFAULT_LENGTH; 设置的大点。我设置成10了。
2.字体设置的小点  WheelOptions.java里面有个	
原来是：	int textSize = (screenheight / 100) * 4;    这里的4改成3
3.然后你自己代码里面，设置数据源的地方，自己限制下省市的字数
final int maxlen = 5;
 if (provname.length() > maxlen) {
          provname = provname.substring(0,maxlen) + "..";
}  我是限制了5个字

这样显示效果就过得去了。
测了下没有明显的bug

iOS程序员，班门弄斧了

**Comment by damon-zhu** [comment]
主要是省市的字数不方便限制，特别是那些少数名族什么旗，什么县的，多的有七八个字，这种又不可能说不显示全的朱维君 ｜ Damon.zhu手机：13862097554邮箱：513809030@qq.com                             原始邮件                             发件人: guoxj<notifications@github.com>收件人: saiwu-bigkoo/Android-PickerView<Android-PickerView@noreply.github.com>抄送: damon-zhu<513809030@qq.com>发送时间: 2015年8月17日(周一) 15:44主题: Re: [Android-PickerView] 省市区三级联动显示有问题 (#7)分享下：
1.ArrayWheelAdapter.java里面有个ArrayWheelAdapter.DEFAULT_LENGTH; 设置的大点。我设置成10了。
2.字体设置的小点  WheelOptions.java里面有个
原来是：    int textSize = (screenheight / 100) * 4;    这里的4改成3
3.然后你自己代码里面，设置数据源的地方，自己限制下省市的字数
final int maxlen = 5;
 if (provname.length() > maxlen) {
          provname = provname.substring(0,maxlen) + "..";
}  我是限制了5个字

这样显示效果就过得去了。
测了下没有明显的bug

iOS程序员，班门弄斧了

**Comment by gzu-liyujiang** [comment]
```java
        int len;
        if (options3Items != null) {
            len = 4;//三级联动选择
        } else if (options2Items != null) {
            len = 10;//二级联动选择
        } else {
            len = 20;//单项选择
        }
       setAdapter(new OptionAdapter(optionsItems, len));
```


```java
    private class OptionAdapter extends WheelArrayAdapter<String> {

        public OptionAdapter(ArrayList<String> items, int length) {
            super(items, length);
        }

        @Override
        public String getItem(int index) {
            String item = super.getItem(index);
            // FIXME: 2015/10/23 如果名称较长，整个文字排版上就容易有问题，故截取显条目字数
            if (optionView3.isShown()) {
                item = cutString(item, 4, "...");
            } else if (optionView2.isShown()) {
                item = cutString(item, 10, "...");
            } else {
                item = cutString(item, 20, "...");
            }
            return item;
        }

        private String cutString(String text, int length, String endWith) {
            //GBK每个汉字长2，UTF-8每个汉字长度为3
            final String CHINESE_ENCODE = "UTF-8";
            final int CHINESE_LENGTH = 3;
            int textLength = text.length();
            int byteLength = 0;
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < textLength && byteLength < length * CHINESE_LENGTH; i++) {
                String str_i = text.substring(i, i + 1);
                if (str_i.getBytes().length == 1) {
                    byteLength++;//英文
                } else {
                    byteLength += CHINESE_LENGTH;//中文
                }
                sb.append(str_i);
            }
            try {
                if (byteLength < text.getBytes(CHINESE_ENCODE).length) {
                    sb.append(endWith);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            return sb.toString();
        }

    }

```

**Comment by snowjade** [comment]
另外可以增加一个状态改变监听器，实时监听三级联动的状态，同步在主界面上显示，这样就算截取了显条目字数，一样可以在界面上看到完整的省市名字。
