### ISSUE TITLE
填写生日时只想出现月和日，建议增加

### ISSUE THREAD

**Issue by vegastar002** [saiwu-bigkoo/Android-PickerView#73]

**Comment by NaughtBoy** [comment]
建议不要用Gradle导入，直接把源码拉下来到自己项目，可以随时定制成自己想要的

**Comment by LomoLin** [comment]
建议可以尝试使用OptionsPickerView

**Comment by saiwu-bigkoo** [comment]
我有考虑过要不要支持没有年的月和日格式，但是闰年的特殊性不选择年的话并不合理，如果你硬要月日可以像楼上说的用OptionsPickerView实现
