### ISSUE TITLE
建议增加“取消”按钮改名和回调方法

### ISSUE THREAD

**Issue by gemini2100** [saiwu-bigkoo/Android-PickerView#74]

**Comment by kangtong** [comment]
我发现可以使用
控件名.setOnDismissListener(new OnDismissListener() {
      @Override public void onDismiss(Object o) {
                    事件
      }
来控制取消的回调

**Comment by saiwu-bigkoo** [comment]
同意楼上。修改按钮名可以在string里面重写同name的字符进行覆盖即可。
