### ISSUE TITLE
希望可以自行修改 "取消"及"確定"的字

### ISSUE THREAD

**Issue by Arthas-Fung** [saiwu-bigkoo/Android-PickerView#75]
如題, 可自行設置繁中, 英文

另外,確定按鍵不是貼最右邊的
我用time picker, 只有年和日的
但左邊多了很多空白地方,都貼到右邊去了

**Comment by NaughtBoy** [comment]
建议不要用Gradle导入，直接把源码拉下来到自己项目，可以随时定制成自己想要的

**Comment by ysmintor** [comment]
把源码放到自己的项目中，再在string.xml中重写你要文字就可以了1

**Comment by saiwu-bigkoo** [comment]
其实不用放源码，你自己项目中的strings.xml里面重写一个同名的属性就可以覆盖了
