### ISSUE TITLE
怎么才能自定义字体大小呢？

### ISSUE THREAD

**Issue by izhangxb** [saiwu-bigkoo/Android-PickerView#83]
默认的字体太大了，除了作为library依赖，修改资源，还有其他方法吗？

**Comment by NaughtBoy** [comment]
建议不要用Gradle导入，直接把源码拉下来到自己项目，可以随时定制成自己想要的。
在WheelTime 的setPicker() 方法里面有设置字体大小的

**Comment by saiwu-bigkoo** [comment]
pickerview_customTextSize 和 pickerview_textsize 到 xml 中 来控制自定义文字大小
