### ISSUE TITLE
返回键的影响

### ISSUE THREAD

**Issue by wl376705253** [saiwu-bigkoo/Android-PickerView#84]
我在fragment中使用这个控件，点击返回按键时 直接将整个碎片销毁 而我希望的是 如果时间选择控件在展示状态时，可以先将其隐藏，在其隐藏后，点击返回按键 ，才销毁碎片。 可以做到么？

**Comment by saiwu-bigkoo** [comment]
你要监听返回键，然后判断是显示了就只dismiss控件然后return true 即可
