### ISSUE TITLE
三级地址联动 可以分批加载吗

### ISSUE THREAD

**Issue by ysmintor** [saiwu-bigkoo/Android-PickerView#87]
## 如题
看Demo都是把数据一次写进去，而三级联动的话我想知道的是可否省每一次全部加载，而我想市级别的由省的当前值来进行加载！

由于把省的数据写了，而市级没有数据的话会报错，所以想知道这个想法是否可行，若可行的话，希望能指点一下！！

一次性加载全国的数据感觉比较耗内存啊！！这个问题有人注意吗？

**Comment by saiwu-bigkoo** [comment]
默认设置不能，你可以进行自定义
