### ISSUE TITLE
README中的Gradle配置

### ISSUE THREAD

**Issue by xingfinal** [saiwu-bigkoo/Android-PickerView#9]
Gradle依赖似乎应该配置成compile 'com.bigkoo:pickerview:1.0.0'吧

**Comment by saiwu-bigkoo** [comment]
非常感谢，两个库同时提交上来编辑的时候都搞混了。

**Comment by xingfinal** [comment]
额.. 应该感谢你们开源这么好的东东, Gradle配置小问题.....
