### ISSUE TITLE
弹出的时候会出现卡顿，并且有延迟

### ISSUE THREAD

**Issue by onionYJK** [saiwu-bigkoo/Android-PickerView#93]
两个activity中一样的代码，第二个activity中弹出的时候会出现卡顿，并且有延迟，这个是什么情况。。。

**Comment by maoruibin** [comment]
因为反射的问题，估计你的可选项数据太多了！

**Comment by xuwj** [comment]
android中尽量避免用反射。

**Comment by onionYJK** [comment]
@xuwj  那么在这个项目里面应该怎么解决这个问题呢？

**Comment by maoruibin** [comment]
在 measure 方法中有一个方法 需要获取 item 的最长长度和最高高度，这个方法使用 for 循环 遍历获取最高和最长的值，如果你的最高高度和最长长度是确定的 可以给死，而不是每次都去计算！这样会节省下一部分性能！

**Comment by saiwu-bigkoo** [comment]
2.1.0已去掉反射
