### ISSUE TITLE
内容重叠

### ISSUE THREAD

**Issue by 522135806** [saiwu-bigkoo/Android-PickerView#98]
在480*800屏幕下，日期与时间同时显示时 如：“yyyy 年MM 月dd 日 HH 时mm 分” ，数字会与年、月、日、时、分重叠。 
![qq 20160623142203](https://cloud.githubusercontent.com/assets/19384322/16293615/e7fe652c-394d-11e6-88c9-071a30c8ae1b.png)

**Comment by saiwu-bigkoo** [comment]
pickerview_customTextSize 和 pickerview_textsize 到 xml 中 来控制自定义文字大小 ，自己定义一下这个分辨率的大小即可
