### ISSUE TITLE
Error:Unable to load class 'org.gradle.internal.logging.LoggingManagerInternal'.

### ISSUE THREAD

**Issue by Freshman111** [saiwu-bigkoo/Android-PickerView#99]
一直报这个错，VPN开着呢

Error:Unable to load class 'org.gradle.internal.logging.LoggingManagerInternal'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by saiwu-bigkoo** [comment]
这个好像不关我的事吧

**Comment by Freshman111** [comment]
确实不管你的事！
但是：
1，这么多star数量的开源库还在用的gradle1.0.0不合适吧。
2，开发者下载你的开源项目，一运行一堆编译错误不合适吧。
3，被人提问题，一句不管我的事不合适吧。

**Comment by saiwu-bigkoo** [comment]
抱歉是我回复不当，gradle版本并不影响项目本身，环境配置问题我也无法保证别人跟我一摸一样的环境，还是要根据开发者自己调整，基本上同步下gradle就可以解决了。

在 2016-06-24 11:46:33，"sgffsg" <notifications@github.com> 写道：


确实不管你的事！
但是：
1，这么多star数量的开源库还在用的gradle1.0.0不合适吧。
2，开发者下载你的开源项目，一运行一堆编译错误不合适吧。
3，被人提问题，一句不管我的事不合适吧。

**Comment by weixinfree** [comment]
支持你一把，鄙视那些只会索取的人，觉得不够好，fix 然后 发起 pr 请求啊。
